const {chromium}=require('/Users/shauryapunj/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const assert=require('assert'),fs=require('fs'),path=require('path');
(async()=>{const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});const results=[];
const cases=[{width:1440},{width:768},{width:390},{width:320,reduced:true},{width:390,noWebGL:true}];
for(const test of cases){const context=await browser.newContext({viewport:{width:test.width,height:test.width===1440?1000:844},reducedMotion:test.reduced?'reduce':'no-preference'});if(test.noWebGL)await context.addInitScript(()=>{const original=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...args){return /webgl/i.test(type)?null:original.call(this,type,...args)}});const page=await context.newPage();page.setDefaultTimeout(15000);page.setDefaultNavigationTimeout(30000);const errors=[],badResponses=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)badResponses.push({url:r.url(),status:r.status()})});const result={...test,errors,badResponses};try{
 await page.goto('http://127.0.0.1:5188/',{waitUntil:'networkidle'});await page.locator('.hero-stage[data-renderer]').waitFor();await page.waitForTimeout(1800);
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth),0,'horizontal overflow');result.renderer=await page.locator('.hero-stage').getAttribute('data-renderer');assert.equal(result.renderer,test.noWebGL?'fallback':'webgl');
 if(!test.reduced&&!test.noWebGL){
 const before=await page.locator('#glass-canvas').getAttribute('data-pose');await page.mouse.move(test.width*.8,300);await page.waitForTimeout(900);const after=await page.locator('#glass-canvas').getAttribute('data-pose');assert.notEqual(before,after,'pointer/ambient pose changes');
 await page.locator('#motion-toggle').click();await page.waitForTimeout(300);const paused=await page.locator('#glass-canvas').getAttribute('data-pose');await page.waitForTimeout(700);assert.equal(paused,await page.locator('#glass-canvas').getAttribute('data-pose'),'ambient motion pauses');await page.locator('#motion-toggle').click();
 await page.evaluate(()=>scrollTo({top:innerHeight*.6,behavior:'instant'}));await page.waitForTimeout(1900);const progress=Number(await page.locator('#glass-canvas').getAttribute('data-progress'));assert(progress>.35,'scroll drives the actual 3D scene');result.scrollProgress=progress;
 }else{assert(await page.locator('body').evaluate(el=>el.classList.contains('hero-static')),'static mode removes scroll sequence');}
 await page.locator('.atelier-menu-toggle').click();await page.waitForTimeout(650);assert(await page.locator('#atelier-menu').evaluate(d=>d.open));await page.keyboard.press('Escape');await page.waitForTimeout(350);assert(!await page.locator('#atelier-menu').evaluate(d=>d.open));assert(await page.locator('.atelier-menu-toggle').evaluate(e=>e===document.activeElement));
 await page.locator('[data-open-search]').click();await page.locator('#atelier-search').fill('velvet');assert.equal(await page.locator('[data-result]').count(),1);await page.locator('[data-result="3"]').click();assert.equal(await page.locator('#atelier-panel-title').innerText(),'Rebel in Velvet');await page.locator('[data-save]').click();assert.equal(await page.locator('.atelier-count').innerText(),'1');await page.keyboard.press('Escape');await page.waitForTimeout(350);
 await page.locator('[data-open-edit]').click();assert.equal(await page.locator('[data-result]').count(),1);await page.locator('[data-remove="3"]').click();assert.equal(await page.locator('.atelier-count').innerText(),'0');await page.keyboard.press('Escape');await page.waitForTimeout(350);
 await page.locator('#collection').evaluate(e=>e.scrollIntoView({behavior:'instant',block:'start'}));await page.waitForTimeout(1400);for(const n of [1,2,0,3]){await page.locator(`[data-scent="${n}"]`).click();await page.waitForTimeout(50)}await page.waitForTimeout(1400);assert.equal(await page.locator('[data-scent="3"]').getAttribute('aria-pressed'),'true');assert.equal(await page.locator('#explore-selected').getAttribute('data-product'),'3');await page.locator('#explore-selected').click();assert.equal(await page.locator('#atelier-panel-title').innerText(),'Rebel in Velvet');await page.keyboard.press('Escape');await page.waitForTimeout(350);
 for(const section of await page.locator('main>section').all()){await section.evaluate(e=>e.scrollIntoView({block:'center',behavior:'instant'}));await page.waitForTimeout(100)}await page.waitForTimeout(1400);
 result.images=await page.locator('main img').evaluateAll(imgs=>imgs.map(i=>({src:i.getAttribute('src'),loaded:i.complete&&i.naturalWidth>0,fit:getComputedStyle(i).objectFit})));assert(result.images.every(i=>i.loaded&&i.fit==='contain'),'all complete editorial images load');
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth),0,'no overflow after interaction');result.brokenAnchors=await page.locator('a[href^="#"]').evaluateAll(es=>es.map(e=>e.getAttribute('href')).filter(h=>h!=='#'&&!document.getElementById(h.slice(1))));assert.equal(result.brokenAnchors.length,0);assert.equal(errors.length,0);assert.equal(badResponses.length,0);result.passed=true;
 if(test.noWebGL||test.reduced){await page.evaluate(()=>scrollTo({top:0,behavior:'instant'}));await page.waitForTimeout(400);await page.screenshot({path:path.join(__dirname,test.noWebGL?'fallback-mobile.png':'reduced-mobile.png')});}
 }catch(e){result.passed=false;result.failure=e.message;await page.screenshot({path:path.join(__dirname,`failure-${test.width}-${test.noWebGL?'fallback':test.reduced?'reduced':'motion'}.png`)}).catch(()=>{});}
 results.push(result);console.log(JSON.stringify({width:test.width,mode:test.noWebGL?'fallback':test.reduced?'reduced':'motion',passed:result.passed,failure:result.failure}));await context.close();}
 const page=await browser.newPage();for(const route of ['00-preserved','01-maison','02-nocturne','03-journal','04-alchemy']){const r=await page.goto(`http://127.0.0.1:5188/${route}/`,{waitUntil:'domcontentloaded'});assert.equal(r.status(),200)}await browser.close();fs.writeFileSync(path.join(__dirname,'checks.json'),JSON.stringify(results,null,2));if(results.some(r=>!r.passed))process.exitCode=1;
})().catch(e=>{console.error(e);process.exitCode=1});
