const {chromium}=require('/Users/shauryapunj/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('fs'),path=require('path'),assert=require('assert');
(async()=>{const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});const report=[];const names=['Silent Storm','The Night Lingers','The Sweetest Stranger','Rebel in Velvet'];
for(const width of (process.env.QA_WIDTHS?process.env.QA_WIDTHS.split(',').map(Number):[1440,390,768,320]))for(const route of (process.env.QA_ROUTES?process.env.QA_ROUTES.split(','):['01-maison','02-nocturne','03-journal'])){
 const reduced=width===320?'reduce':'no-preference';const context=await browser.newContext({viewport:{width,height:width===1440?1000:844},reducedMotion:reduced});const page=await context.newPage();page.setDefaultTimeout(10000);page.setDefaultNavigationTimeout(30000);const errors=[];page.on('pageerror',e=>errors.push(e.message));const result={route,width,reduced,errors};
 try{await page.goto(`http://127.0.0.1:5174/${route}/`,{waitUntil:'networkidle'});await page.waitForTimeout(1800);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth),0,'page overflow');if(width===1440||width===390)await page.screenshot({path:path.join(__dirname,`${route}-${width}-hero.png`)});
 await page.locator('.atelier-menu-toggle').click();await page.waitForTimeout(600);assert(await page.locator('#atelier-menu').evaluate(d=>d.open),'menu opens');await page.keyboard.press('Escape');await page.waitForTimeout(350);assert(!await page.locator('#atelier-menu').evaluate(d=>d.open),'menu closes');assert(await page.locator('.atelier-menu-toggle').evaluate(el=>el===document.activeElement),'menu restores focus');
 await page.locator('[data-open-search]').click();await page.locator('#atelier-search').fill('Velvet');assert.equal(await page.locator('[data-result]').count(),1,'search narrows collection');await page.locator('[data-result="3"]').click();assert.equal(await page.locator('#atelier-panel-title').innerText(),names[3]);await page.locator('[data-save]').click();assert.equal(await page.locator('.atelier-count').innerText(),'1');await page.keyboard.press('Escape');await page.waitForTimeout(350);await page.reload({waitUntil:'networkidle'});assert.equal(await page.locator('.atelier-count').innerText(),'1','selection persists reload');
 await page.locator('[data-open-edit]').click();await page.locator('[data-remove="3"]').click();assert.equal(await page.locator('.atelier-count').innerText(),'0');assert(await page.locator('.atelier-empty').isVisible());await page.keyboard.press('Escape');await page.waitForTimeout(350);
 await page.locator('[data-open-search]').click();await page.locator('#atelier-search').fill('nonexistent');assert.equal(await page.locator('[data-result]').count(),0);assert(await page.locator('.atelier-empty').isVisible());await page.keyboard.press('Escape');await page.waitForTimeout(350);
 await page.locator('#collection').evaluate(e=>e.scrollIntoView({block:'start',behavior:'instant'}));await page.waitForTimeout(1300);
 const selector=route==='01-maison'?'[data-scent]':route==='02-nocturne'?'[data-fragrance]':'[data-mood]';const choice=page.locator(selector);for(const n of [1,2,0,3]){await choice.nth(n).click();await page.waitForTimeout(60)}await page.waitForTimeout(1500);const activeAttr=route==='03-journal'?'aria-selected':'aria-pressed';assert.equal(await choice.nth(3).getAttribute(activeAttr),'true');const action=page.locator(route==='01-maison'?'#selected-discover':route==='02-nocturne'?'.product-link':'.portrait-action');assert.equal(await action.getAttribute('data-product'),'3','last requested fragrance wins');await action.click();assert.equal(await page.locator('#atelier-panel-title').innerText(),names[3]);if(width===390&&route==='01-maison')await page.waitForTimeout(700);if(width===390&&route==='01-maison')await page.screenshot({path:path.join(__dirname,'mobile-product-panel.png')});await page.keyboard.press('Escape');await page.waitForTimeout(350);
 await choice.nth(0).click();await page.waitForTimeout(1400);await page.locator('#collection').evaluate(e=>e.scrollIntoView({block:'start',behavior:'instant'}));await page.waitForTimeout(1800);if(width===1440||width===390)await page.screenshot({path:path.join(__dirname,`${route}-${width}-collection.png`)});
 const sections=await page.locator('main>section').all();for(const section of sections){await section.evaluate(e=>e.scrollIntoView({block:'center',behavior:'instant'}));await page.waitForTimeout(100)}await page.waitForTimeout(1600);result.images=await page.locator('main img').evaluateAll(imgs=>imgs.map(i=>({src:i.getAttribute('src'),loaded:i.complete&&i.naturalWidth>0,fit:getComputedStyle(i).objectFit})));assert(result.images.every(i=>i.loaded),'all images loaded');assert(result.images.every(i=>i.fit==='contain'),'intact image frames');assert(result.images.every(i=>new URL(i.src,'http://localhost').pathname.startsWith('/media/editorial/')),'only approved photography');
 result.brokenAnchors=await page.locator('a[href^="#"]').evaluateAll(links=>links.map(a=>a.getAttribute('href')).filter(h=>h!=='#'&&!document.getElementById(h.slice(1))));assert.equal(result.brokenAnchors.length,0);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth),0,'end page overflow');assert.equal(errors.length,0,'no runtime errors');result.passed=true;
 }catch(e){result.passed=false;result.failure=e.message;await page.screenshot({path:path.join(__dirname,`${route}-${width}-failure.png`)}).catch(()=>{})}
 report.push(result);console.log(JSON.stringify({route,width,passed:result.passed,failure:result.failure}));await context.close();}
 await browser.close();fs.writeFileSync(path.join(__dirname,process.env.QA_REPORT||'checks.json'),JSON.stringify(report,null,2));if(report.some(x=>!x.passed))process.exitCode=1;
})().catch(e=>{console.error(e);process.exitCode=1});
