import './style.css';
import gsap from 'gsap';
import {products,families} from './catalog.js';
import {initialState,parseRoute,reduce,recommend} from './state.js';
import {Ambience} from './audio.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
// Mounted inside the main site under /feel-your-fragrance/
const paths={home:'/feel-your-fragrance/',intensity:'/feel-your-fragrance/quiz',notes:'/feel-your-fragrance/quiz/1',collection:'/feel-your-fragrance/layering'};
let state={...initialState,...parseRoute(location.pathname)};
const reducedQuery=matchMedia('(prefers-reduced-motion: reduce)'),finePointerQuery=matchMedia('(hover: hover) and (pointer: fine)');let reduced=reducedQuery.matches,paused=reduced,motionPausedByUser=false,scene,transition,viewTransition,listReveal,navigationId=0;let thumbnails=[];
const ambience=new Ambience(),stage=$('#stage'),loading=$('#loading'),detail=$('#detail-dialog'),menu=$('#menu-dialog');
function render({syncScreen=true,keepListHidden=false}={}){
 document.body.className=`is-${state.screen} screen-${state.screen}${state.screen==='collection'&&state.view==='list'?' list-view':''}${document.body.classList.contains('render-fallback')?' render-fallback':''}`;
 if(syncScreen)$$('.screen').forEach(el=>el.hidden=el.id!==state.screen);
 $('#intensity-range').value=state.intensity;$('.range-wrap').style.setProperty('--position',`${state.intensity}%`);$('#family-title').innerHTML=families[state.family].title;
 const p=products[state.selected];$('#product-caption').innerHTML=`<span class="product-index">${String(state.selected+1).padStart(2,'0')} / 04</span><h1>${p.name.toUpperCase()}</h1><p>${p.family}</p>`;
 $$('.view-switch button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===state.view)));if(!keepListHidden)$('#product-list').hidden=state.view!=='list';$('.gallery-caption').inert=state.view==='list';$('.gallery-caption').setAttribute('aria-hidden',String(state.view==='list'));$$('.product-card').forEach((b,i)=>b.setAttribute('aria-pressed',String(i===state.selected)));$$('.fallback-products img').forEach((img,i)=>img.classList.toggle('selected',i===state.selected));
 document.title=`${state.screen==='home'?'The Signature Collection':state.screen==='collection'?p.name:'Find Your Fragrance'} — Vāsa`;
}
function navigate(screen,{push=true}={}){
 if(!paths[screen])return;const previous=state.screen,changed=previous!==screen,id=++navigationId;state=reduce(state,{type:'screen',screen});if(push&&location.pathname!==paths[screen])history.pushState({},'',paths[screen]);
 if(menu.open)menu.close();$('#menu-toggle').setAttribute('aria-expanded','false');if(detail.open)detail.close();transition?.kill();viewTransition?.kill();clearTimeout(listReveal);
 const outgoing=$(`#${previous}`),incoming=$(`#${screen}`);$$('.screen').forEach(el=>{if(el!==outgoing&&el!==incoming)el.hidden=true;});render({syncScreen:false});scene?.setState(state);
 if(!changed||reduced){$$('.screen').forEach(el=>el.hidden=el!==incoming);gsap.set(incoming,{clearProps:'opacity,transform'});}
 else {outgoing.hidden=false;incoming.hidden=false;gsap.set(outgoing,{opacity:1});transition=gsap.timeline({onComplete:()=>{if(id!==navigationId)return;outgoing.hidden=true;gsap.set([outgoing,incoming],{clearProps:'opacity,transform'});}}).to(outgoing,{opacity:0,y:-8,duration:.28,ease:'power1.in'},0).fromTo(incoming,{opacity:0,y:10},{opacity:1,y:0,duration:.62,ease:'power2.out'},.16);}
 $('#announcement').textContent=screen==='collection'?'Collection gallery':screen==='intensity'?'Question one: fragrance character':screen==='notes'?'Question two: fragrance family':'Vasa home';
}
function chooseProduct(index){state=reduce(state,{type:'select',index});render({syncScreen:false});scene?.setState(state);if(!reduced)gsap.fromTo('#product-caption',{opacity:0,y:8},{opacity:1,y:0,duration:.7,overwrite:'auto'});}
function chooseFamily(index){state=reduce(state,{type:'family',index});render({syncScreen:false});scene?.setState(state);if(!reduced)gsap.fromTo('#family-title',{opacity:0,y:12},{opacity:1,y:0,duration:.7,overwrite:'auto'});}
function openDialog(html){$('#dialog-content').innerHTML=html;detail.showModal();}
function updateMotion(){scene?.setPaused(paused);const motion=$('#motion');motion.setAttribute('aria-pressed',String(paused));motion.setAttribute('aria-label',paused?'Resume ambient motion':'Pause ambient motion');motion.dataset.motion=paused?'paused':'playing';$('.motion-icon-pause').hidden=paused;$('.motion-icon-play').hidden=!paused;}
function showProduct(){const p=products[state.selected];openDialog(`<p class="eyebrow">THE SIGNATURE COLLECTION · ${String(state.selected+1).padStart(2,'0')}</p><img class="dialog-bottle" src="${thumbnails[state.selected]||`/brand/${p.id}.webp`}" alt="${p.name} bottle"><h2>${p.name}</h2><p>${p.description}</p>${p.notes.map(([label,text])=>`<h3>${label}</h3><p>${text}</p>`).join('')}<button class="rule-action" id="back-collection">BACK TO THE COLLECTION</button>`);$('#back-collection').onclick=()=>detail.close();}
async function toggleSound(){try{const enabled=await ambience.toggle();$('#sound').setAttribute('aria-pressed',String(enabled));$('#sound').setAttribute('aria-label',enabled?'Mute ambient sound':'Enable ambient sound');}catch{$('#announcement').textContent='Audio is unavailable in this browser.';}}
function showSettings(){openDialog(`<p class="eyebrow">MAKE YOURSELF AT HOME</p><h2>Your experience</h2><div class="setting-row"><span>Ambient motion</span><button id="setting-motion">${paused?'Paused':'Playing'}</button></div><div class="setting-row"><span>Ambient sound</span><button id="setting-sound">${ambience.enabled?'On':'Off'}</button></div><p>Sound is always off when you arrive. Your device’s reduced-motion preference is respected.</p>`);$('#setting-motion').onclick=()=>{paused=!paused;motionPausedByUser=paused;updateMotion();$('#setting-motion').textContent=paused?'Paused':'Playing';};$('#setting-sound').onclick=async()=>{await toggleSound();$('#setting-sound').textContent=ambience.enabled?'On':'Off';};}
$$('[data-route]').forEach(link=>link.addEventListener('click',e=>{e.preventDefault();navigate(link.dataset.route);}));$('#brand').addEventListener('click',e=>{e.preventDefault();navigate('home');});window.addEventListener('popstate',()=>navigate(parseRoute(location.pathname).screen,{push:false}));
$('#intensity-range').addEventListener('input',e=>{state=reduce(state,{type:'intensity',value:e.target.value});$('.range-wrap').style.setProperty('--position',`${state.intensity}%`);scene?.setIntensity(state.intensity);});
$$('[data-family]').forEach(b=>b.onclick=()=>chooseFamily(state.family+Number(b.dataset.family)));$$('[data-product]').forEach(b=>b.onclick=()=>chooseProduct(state.selected+Number(b.dataset.product)));
function chooseView(view){
 if(view===state.view)return;viewTransition?.kill();clearTimeout(listReveal);
 state=reduce(state,{type:'view',view});
 const list=$('#product-list');
 if(state.view==='list'){
  list.hidden=true;render({syncScreen:false,keepListHidden:true});scene?.setState(state);
  listReveal=setTimeout(()=>{if(state.screen!=='collection'||state.view!=='list')return;list.hidden=false;$$('.product-card')[state.selected]?.scrollIntoView({behavior:reduced?'instant':'smooth',block:'nearest',inline:'center'});if(!reduced)viewTransition=gsap.fromTo(list,{opacity:0,y:20},{opacity:1,y:0,duration:.62,ease:'power2.out',clearProps:'opacity,transform'});},reduced?0:120);
 }else{render({syncScreen:false});scene?.setState(state);}
}
$$('[data-view]').forEach(b=>b.onclick=()=>chooseView(b.dataset.view));
$('#discover-result').onclick=()=>{state=reduce(state,{type:'select',index:recommend(families[state.family].id,state.intensity)});state=reduce(state,{type:'view',view:'gallery'});navigate('collection');};$('#explore-product').onclick=showProduct;
$('#info').onclick=()=>openDialog(`<p class="eyebrow">THE CHARACTER OF YOUR FRAGRANCE</p><h2>Luminous or opulent?</h2><h3>Luminous</h3><p>Airy, radiant and gently present. Think fresh openings, delicate florals and lighter woods.</p><h3>Opulent</h3><p>Warm, enveloping and full of depth. Think amber, rich florals, smoky woods and oud.</p><p>Move the sphere to the character you feel drawn to. There is no wrong answer.</p>`);
$('#menu-toggle').onclick=()=>{menu.showModal();$('#menu-toggle').setAttribute('aria-expanded','true');};menu.addEventListener('close',()=>$('#menu-toggle').setAttribute('aria-expanded','false'));$$('.dialog-close').forEach(b=>b.onclick=()=>b.closest('dialog').close());
[detail,menu].forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}}));
$('#motion').onclick=()=>{paused=!paused;motionPausedByUser=paused;updateMotion();};$('#sound').onclick=toggleSound;$('#settings').onclick=showSettings;
$('#privacy').onclick=()=>openDialog(`<p class="eyebrow">YOUR PRIVACY</p><h2>A quiet, private experience.</h2><p>This standalone Vasa preview does not collect your answers, use analytics, send personal information, or set tracking cookies. Your fragrance choices exist only in this open page.</p><p>Fonts, artwork and application files are served locally. Sound is synthesized in your browser only when you enable it.</p>`);
reducedQuery.addEventListener('change',e=>{reduced=e.matches;paused=reduced||motionPausedByUser;if(scene)scene.reduced=reduced;updateMotion();});
let drag=null;window.addEventListener('pointermove',e=>{if(drag&&state.screen==='collection'&&state.view==='gallery')scene?.setDrag((e.clientX-drag.x)/innerWidth);},{passive:true});window.addEventListener('pointerdown',e=>{if(e.target.closest('button,a,input,dialog,#product-list'))return;drag={x:e.clientX,y:e.clientY};});window.addEventListener('pointerup',e=>{if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;drag=null;scene?.setDrag(0);if(Math.abs(dx)<45||Math.abs(dx)<Math.abs(dy))return;if(state.screen==='collection'&&state.view==='gallery')chooseProduct(state.selected+(dx<0?1:-1));if(state.screen==='notes')chooseFamily(state.family+(dx<0?1:-1));});window.addEventListener('pointercancel',()=>{drag=null;scene?.setDrag(0);});
window.addEventListener('keydown',e=>{if(menu.open||detail.open||e.target.matches('input'))return;if(!['ArrowRight','ArrowLeft'].includes(e.key))return;const dir=e.key==='ArrowRight'?1:-1;if(state.screen==='collection'&&state.view==='gallery'){e.preventDefault();chooseProduct(state.selected+dir);}if(state.screen==='notes'){e.preventDefault();chooseFamily(state.family+dir);}});
const cursor=$('#cursor');let cp={x:innerWidth/2,y:innerHeight/2},target={...cp};function updateCursorMode(){if(!finePointerQuery.matches||reduced)cursor.style.opacity='0';}window.addEventListener('pointermove',e=>{if(!finePointerQuery.matches||e.pointerType==='touch'||reduced)return;target.x=e.clientX;target.y=e.clientY;cursor.style.opacity='.7';cursor.classList.toggle('over',!!e.target.closest('button,a,input,[role="button"]'));},{passive:true});document.addEventListener('pointerleave',()=>cursor.style.opacity='0');window.addEventListener('blur',()=>cursor.style.opacity='0');finePointerQuery.addEventListener('change',updateCursorMode);gsap.ticker.add(()=>{if(reduced||!finePointerQuery.matches)return;cp.x+=(target.x-cp.x)*.13;cp.y+=(target.y-cp.y)*.13;cursor.style.transform=`translate3d(${cp.x}px,${cp.y}px,0)`;});
function makeList(){$('#product-list').innerHTML=products.map((p,i)=>`<button class="product-card" data-index="${i}" aria-label="Select ${p.name}" aria-pressed="${i===state.selected}"><h2>${p.lines.join('<br>')}</h2><img src="${thumbnails[i]||`/brand/${p.id}.webp`}" alt="${p.name} bottle" draggable="false"><span class="card-no">0${i+1}</span></button>`).join('');$$('.product-card').forEach(b=>b.onclick=()=>chooseProduct(Number(b.dataset.index)));}
function ready(images){thumbnails=images;makeList();scene?.setState(state,true);scene?.enter();loading.style.opacity='0';setTimeout(()=>loading.remove(),850);updateMotion();}
function fallback(error){console.warn('Vasa scene fallback:',error.message);scene?.dispose();scene=null;stage.innerHTML=`<div class="fallback-products">${products.map((p,i)=>`<img class="${i===state.selected?'selected':''}" src="/brand/${p.id}.webp" alt="">`).join('')}</div>`;document.body.classList.add('render-fallback');ready([]);$('#announcement').textContent='Your browser is showing the still-image collection. All fragrance controls remain available.';}
render();makeList();updateMotion();import('./scene.js').then(({ExperienceScene})=>{scene=new ExperienceScene(stage,{reduced,onReady:ready,onFail:fallback});}).catch(fallback);window.addEventListener('pagehide',e=>{if(!e.persisted){scene?.dispose();ambience.dispose();}});
