const{chromium}=require('/Users/shauryapunj/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});const results=[];
for(const width of[1440,768,390,320]){const context=await browser.newContext({viewport:{width,height:900},reducedMotion:width===320?'reduce':'no-preference'});const page=await context.newPage();const errors=[],bad=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)bad.push(r.url())});const result={width,errors,bad};try{
 await page.goto('http://127.0.0.1:5188/',{waitUntil:'networkidle'});await page.waitForTimeout(1400);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth),0,'initial overflow');await page.screenshot({path:`qa/campaign/hero-${width}.png`});
 await page.locator('[data-panel="search"]').first().click();await page.locator('#fragrance-search').fill('rose');assert.equal(await page.locator('.search-result').count(),2);await page.locator('#fragrance-search').fill('<img src=x onerror=alert(1)>');assert.equal(await page.locator('.search-results img').count(),0);await page.locator('#fragrance-search').fill('cedar');await page.locator('.search-result').click();assert.equal(await page.locator('#panel-title').innerText(),'Silent Storm');await page.locator('#panel [data-add]').click();assert.equal(await page.locator('#panel-title').innerText(),'Your bag');assert.equal(await page.locator('#bag-count').innerText(),'1');
 await page.locator('[aria-label="Increase Silent Storm quantity"]').click();assert.equal(await page.locator('#bag-count').innerText(),'2');await page.keyboard.press('Enter');assert.equal(await page.locator('#bag-count').innerText(),'3');await page.keyboard.press('Escape');assert.equal(await page.locator('#panel').evaluate(e=>e.open),false);
 await page.reload({waitUntil:'networkidle'});assert.equal(await page.locator('#bag-count').innerText(),'3');await page.locator('.bag-button').click();await page.locator('[data-remove]').click();assert.equal(await page.locator('.bag-item').count(),0);await page.keyboard.press('Escape');
 if(width<761){await page.locator('.mobile-menu').click();await page.locator('#panel [data-panel="profile"]').click();assert.equal(await page.locator('#panel-title').innerText(),'Your profile');await page.keyboard.press('Escape');}
 await page.locator('.story-stage').scrollIntoViewIfNeeded();await page.locator('#story-pause').evaluate(b=>{if(b.getAttribute('aria-label').startsWith('Pause'))b.click()});await page.locator('[data-slide="0"]').click();await page.waitForTimeout(1600);await page.locator('#story-next').click();await page.locator('#story-next').click();await page.waitForTimeout(2900);assert.equal(await page.locator('#story-counter').innerText(),'03 / 04');assert.equal(await page.locator('.story-slide:not([hidden])').count(),1);assert.equal(await page.locator('.story-slide').nth(2).evaluate(e=>e.style.getPropertyValue('--scent')),'#bbb0c8');
 const active=page.locator('.story-slide:not([hidden]) [data-product]');await active.focus();await page.keyboard.press('ArrowRight');await page.waitForTimeout(1600);assert.equal(await page.locator('.story-stage').evaluate(e=>document.activeElement===e),true);assert.equal(await page.locator('#story-counter').innerText(),'04 / 04');await page.locator('#story-next').click();await page.waitForTimeout(1600);assert.equal(await page.locator('#story-counter').innerText(),'01 / 04');
 await page.locator('.story-stage').screenshot({path:`qa/campaign/carousel-${width}.png`});for(const section of await page.locator('main>section').all()){await section.scrollIntoViewIfNeeded();await page.waitForTimeout(350)}await page.waitForTimeout(900);await page.screenshot({path:`qa/campaign/full-${width}.png`,fullPage:true});
 result.images=await page.locator('main img').evaluateAll(es=>es.filter(e=>e.getBoundingClientRect().height).map(e=>({loaded:e.complete&&e.naturalWidth>0,fit:getComputedStyle(e).objectFit,src:e.getAttribute('src')})));assert(result.images.every(i=>i.loaded&&i.fit==='contain'));assert(result.images.every(i=>i.src.startsWith('/media/campaign/')));assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth),0,'final overflow');assert.equal(errors.length,0);assert.equal(bad.length,0);result.passed=true;
 }catch(e){result.passed=false;result.failure=e.message;await page.screenshot({path:`qa/campaign/failure-${width}.png`}).catch(()=>{})}results.push(result);console.log(JSON.stringify({width,passed:result.passed,failure:result.failure}));await context.close();}
 const page=await browser.newPage();for(const r of['00-preserved','01-maison','02-nocturne','03-journal','04-alchemy','05-campaign'])assert.equal((await page.goto(`http://127.0.0.1:5188/${r}/`,{waitUntil:'domcontentloaded'})).status(),200);
 await browser.close();fs.writeFileSync('qa/campaign/results.json',JSON.stringify(results,null,2));if(results.some(r=>!r.passed))process.exitCode=1;
})().catch(e=>{console.error(e);process.exitCode=1});
