import { gsap, reduced, smoothScroll, ScrollTrigger } from './motion.js';
export const fragrances=[
 {name:'Silent Storm',mood:'The quiet presence',image:'maison-detail',text:'Some things do not need to announce themselves. Meet Silent Storm: an invitation to make a quiet moment your own.'},
 {name:'The Night Lingers',mood:'After the last light',image:'nocturne-ritual',text:'For the moments you are not quite ready to leave. Discover The Night Lingers, and follow the feeling a little further.'},
 {name:'The Sweetest Stranger',mood:'An unexpected connection',image:'journal-stranger',text:'A glance. A conversation. An unexpected connection. The Sweetest Stranger is a name for the possibilities in between.'},
 {name:'Rebel in Velvet',mood:'Softness with an edge',image:'journal-velvet',text:'Softness and a little defiance. Meet Rebel in Velvet, a personal expression that follows its own instinct.'}
];
const imagePath=n=>`/media/editorial/${n}.webp`;
const roll=s=>`<span class="atelier-roll"><span>${s}</span><span aria-hidden="true">${s}</span></span>`;
export function initAtelier({theme='light',collection='#collection',house='#house'}={}){
 const lenis=smoothScroll();let lastFocus=null,toastTimer,closeTween,selected=0;
 let saved=[];try{saved=JSON.parse(localStorage.getItem('vasa-personal-edit')||'[]').filter(n=>Number.isInteger(n)&&n>=0&&n<4)}catch{}
 saved=[...new Set(saved)];
 document.body.insertAdjacentHTML('afterbegin',`<a class="atelier-skip" href="#main">Skip to content</a><header class="atelier-header" data-theme="${theme}"><div class="atelier-glass" aria-hidden="true">${[4,8,12,18].map((b,i)=>`<i style="--b:${b}px;--stop:${18+i*14}%"></i>`).join('')}</div><div class="atelier-header-left"><button class="atelier-menu-toggle" aria-haspopup="dialog" aria-expanded="false" aria-controls="atelier-menu"><span class="atelier-menu-icon" aria-hidden="true"></span>${roll('Menu')}</button><a class="atelier-desktop" href="${collection}">${roll('Fragrances')}</a></div><a class="atelier-logo" href="#main" aria-label="VASA home">vasa</a><div class="atelier-header-right"><button data-open-search aria-haspopup="dialog">${roll('Search')}</button><button data-open-edit aria-haspopup="dialog" aria-label="My edit, ${saved.length} fragrances"><span class="atelier-edit-label">My edit</span><span class="atelier-count">${saved.length}</span></button></div></header>`);
 document.body.insertAdjacentHTML('beforeend',`<dialog id="atelier-menu" class="atelier-dialog atelier-menu" aria-label="Explore VASA"><button class="atelier-dialog-close" data-close aria-label="Close menu">×</button><div class="atelier-menu-grid"><div class="atelier-menu-main"><span class="atelier-label">VASA / THE HOUSE OF FRAGRANCE</span><nav class="atelier-menu-links" aria-label="Explore"><a href="${collection}"><small>01</small> The fragrances</a><a href="${house}"><small>02</small> Our family</a><a href="${collection}" data-menu-search><small>03</small> Find your scent</a></nav><div class="atelier-menu-foot"><span>ROOTED IN FAMILY.</span><span>WORN YOUR WAY.</span></div></div><div class="atelier-menu-visual"><img src="${imagePath(theme==='dark'?'nocturne-hero':'maison-pair')}" alt="VASA fragrance campaign" width="1536" height="1024"><p>A personal world.<br>A lasting impression.</p></div></div></dialog><dialog id="atelier-panel" class="atelier-dialog atelier-panel" aria-labelledby="atelier-panel-title"><button class="atelier-dialog-close" data-close aria-label="Close panel">×</button><div class="atelier-panel-inner"></div></dialog><div class="atelier-toast" role="status" aria-live="polite"></div>`);
 const header=document.querySelector('.atelier-header'),menu=document.querySelector('#atelier-menu'),panel=document.querySelector('#atelier-panel'),inner=panel.querySelector('.atelier-panel-inner'),toggle=document.querySelector('.atelier-menu-toggle');
 function onScroll(){header.classList.toggle('is-scrolled',scrollY>30)}addEventListener('scroll',onScroll,{passive:true});onScroll();
 function announce(s){const t=document.querySelector('.atelier-toast');t.textContent=s;clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.textContent='',2800)}
 function persist(){try{localStorage.setItem('vasa-personal-edit',JSON.stringify(saved))}catch{}document.querySelector('.atelier-count').textContent=saved.length;document.querySelector('[data-open-edit]').setAttribute('aria-label',`My edit, ${saved.length} fragrances`)}
 function show(d){closeTween?.kill();[menu,panel].forEach(x=>{if(x.open&&x!==d)x.close()});lastFocus=document.activeElement;lenis?.stop();document.documentElement.style.overflow='hidden';gsap.set(d,{clearProps:'all'});d.showModal();if(d===menu){toggle.setAttribute('aria-expanded','true');if(!reduced.matches){gsap.fromTo(menu,{opacity:0},{opacity:1,duration:.3});gsap.fromTo(menu.querySelector('.atelier-menu-main'),{y:45,opacity:0},{y:0,opacity:1,duration:.95,ease:'power3.out'});gsap.fromTo(menu.querySelectorAll('.atelier-menu-links a'),{y:60,opacity:0,filter:'blur(6px)'},{y:0,opacity:1,filter:'blur(0px)',duration:1.05,stagger:.1,ease:'power3.out',delay:.12});gsap.fromTo(menu.querySelector('.atelier-menu-visual'),{opacity:0},{opacity:1,duration:1.3,delay:.22});}}else if(!reduced.matches)gsap.fromTo(panel,{x:50,opacity:0,filter:'blur(4px)'},{x:0,opacity:1,filter:'blur(0px)',duration:.55,ease:'power3.out'});}
 function close(d,after){if(!d.open){after?.();return}closeTween?.kill();const finish=()=>{d.close();gsap.set(d,{clearProps:'all'});after?.()};if(reduced.matches)finish();else closeTween=gsap.to(d,{opacity:0,duration:.25,onComplete:finish});}
 [menu,panel].forEach(d=>{d.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();close(d)}},true);d.addEventListener('cancel',e=>{e.preventDefault();close(d)});d.addEventListener('close',()=>{toggle.setAttribute('aria-expanded',String(menu.open));if(!menu.open&&!panel.open){document.documentElement.style.overflow='';lenis?.start();if(lastFocus?.isConnected)lastFocus.focus({preventScroll:true});}});d.querySelector('[data-close]').onclick=()=>close(d);d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right)close(d)}})});
 toggle.onclick=()=>show(menu);
 menu.querySelectorAll('nav a').forEach(a=>a.onclick=e=>{e.preventDefault();close(menu,()=>{if(a.hasAttribute('data-menu-search'))search();else{const target=document.querySelector(a.getAttribute('href'));if(lenis)lenis.scrollTo(target,{offset:-82,duration:1.5});else target?.scrollIntoView();}})});
 function openProduct(index){selected=Number(index);const f=fragrances[selected];if(!f)return;inner.innerHTML=`<span class="atelier-label">THE VASA COLLECTION / 0${selected+1}</span><h2 id="atelier-panel-title">${f.name}</h2><span class="atelier-label">${f.mood}</span><img class="atelier-product-photo" src="${imagePath(f.image)}" alt="${f.name}, complete VASA perfume bottle"><p>${f.text}</p><div class="atelier-product-sub"><span>Concentration · Presence · Time</span><span>VASA PARFUMS</span></div><button class="atelier-action" data-save>${saved.includes(selected)?'Saved to my edit':'Save to my edit'} <span>${saved.includes(selected)?'✓':'＋'}</span></button><p class="atelier-status">Save a fragrance to your edit, then explore the rest of the collection at your own pace.</p>`;inner.querySelector('[data-save]').onclick=()=>{if(saved.includes(selected)){saved=saved.filter(n=>n!==selected);announce(`${f.name} removed from your edit`)}else{saved.push(selected);announce(`${f.name} saved to your edit`)}persist();inner.querySelector('[data-save]').innerHTML=`${saved.includes(selected)?'Saved to my edit':'Save to my edit'} <span>${saved.includes(selected)?'✓':'＋'}</span>`};if(!panel.open)show(panel);else{panel.scrollTop=0;panel.querySelector('[data-close]').focus();}}
 const row=(n,edit=false)=>{const f=fragrances[n];return `<div class="atelier-result"><img src="${imagePath(f.image)}" alt="" width="105" height="95"><button data-result="${n}">${f.name}<small>${f.mood}</small></button>${edit?`<button class="atelier-remove" data-remove="${n}" aria-label="Remove ${f.name}">×</button>`:'<span aria-hidden="true">↗</span>'}</div>`};
 function bindResults(){inner.querySelectorAll('[data-result]').forEach(b=>b.onclick=()=>openProduct(b.dataset.result));}
 function search(){inner.innerHTML=`<span class="atelier-label">FIND SOMETHING PERSONAL</span><h2 id="atelier-panel-title">The fragrances</h2><label class="atelier-label" for="atelier-search">Search by name or mood</label><input id="atelier-search" class="atelier-search-input" type="search" placeholder="Begin with a feeling…" autocomplete="off"><p id="atelier-search-status" class="atelier-status" role="status">4 fragrances</p><div class="atelier-results"></div>`;const input=inner.querySelector('input'),results=inner.querySelector('.atelier-results');function filter(){const query=input.value.trim().toLowerCase();const list=fragrances.flatMap((f,n)=>`${f.name} ${f.mood}`.toLowerCase().includes(query)?[n]:[]);results.innerHTML=list.length?list.map(n=>row(n)).join(''):'<p class="atelier-empty">No fragrance matches that search. Try “quiet”, “night” or “velvet”.</p>';inner.querySelector('#atelier-search-status').textContent=`${list.length} fragrance${list.length===1?'':'s'}`;bindResults();}filter();input.oninput=filter;show(panel);input.focus();}
 function edit(){inner.innerHTML=`<span class="atelier-label">A COLLECTION OF YOUR OWN</span><h2 id="atelier-panel-title">My edit</h2><p>Keep the fragrances that caught your attention. Your selection stays here for your next visit.</p><div>${saved.length?saved.map(n=>row(n,true)).join(''):'<p class="atelier-empty">Your edit is waiting to begin. Explore the collection and save a fragrance that feels like you.</p>'}</div><button class="atelier-action" data-explore>Explore the collection <span>↗</span></button>`;bindResults();inner.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{saved=saved.filter(n=>n!==Number(b.dataset.remove));persist();edit()});inner.querySelector('[data-explore]').onclick=()=>close(panel,()=>{const t=document.querySelector(collection);if(lenis)lenis.scrollTo(t,{offset:-82});else t?.scrollIntoView()});if(!panel.open)show(panel);}
 document.querySelector('[data-open-search]').onclick=search;document.querySelector('[data-open-edit]').onclick=edit;
 document.addEventListener('click',e=>{const b=e.target.closest('[data-product]');if(b){e.preventDefault();openProduct(b.dataset.product)}});
 document.fonts.ready.then(()=>ScrollTrigger.refresh());
 return {lenis,openProduct,search,edit};
}
